### ISSUE TITLE
能否提供渲染好的SHREC17数据集

### ISSUE THREAD

**Issue by zhaoxinv587** [auniquesun/View-GCN-DDP#1]
非常感谢你们提供的检索代码，由于我设备的原因，我无法进行shrec17数据集的多视图渲染，如果您能提供给我那将非常感谢！

这是我的邮箱：2335959784@qq.com

**Comment by auniquesun** [comment]
@zhaoxinv587 我最近在整理相应的代码和数据集，预计9月份发布到 [这个项目](https://github.com/auniquesun/viewformer)，敬请期待

**Comment by auniquesun** [comment]
@zhaoxinv587 渲染好的shrec17数据集百度网盘链接在[这里](https://pan.baidu.com/s/1P0GKOSovIrTbtSAsP5l4Xg?pwd=9jvi )，提取码是 `9jvi`，请下载。
