### ISSUE TITLE
shrec17 rendered views and file "test.csv"

### ISSUE THREAD

**Issue by RyanG41** [auniquesun/View-GCN-DDP#2]
Hi,

Thanks for the updated version of the codebase, it is really helpful!

I encountered a problem when rendering views using that Matlab script, it produces nothing and I'm not so familiar with matlab grammar, could you kindly share the processed shrec17 dataset (百度云), since the link in another issue has expired?

Also, when I try to run the code of retrieval task, it says no such file of "test.csv". I check the shrec17 dataset I downloaded (which is a zip file of size ~50GB), and it appears that only "train.scv" and "val.csv" are included. Could you give me some advice, or share the "test.csv" file?

Very much appreciated for any help!

**Comment by RyanG41** [comment]
Have found those files in another repository "VSFormer", thanks a lot for the provided data!

**Comment by auniquesun** [comment]
@RyanG41 Exactly! The dataset and README are provided in the VSFormer repository.
